### ISSUE TITLE
Show number of errors/pending/undefined in tinyicon

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-html#11]
See http://tommoor.github.com/tinycon/

If there are errors, show a red icon with number of errors
Else if there are pending/undefined, show yellow icon with number of pending+undefined
Else show green icon with total number of passed

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
