### ISSUE TITLE
Allow exporting HTML report in one file

### ISSUE THREAD

**Issue by matthauck** [cucumber/cucumber-html#27]
I like how the ruby cucumber html output did (or still does?) output its html file in one big file, as opposed to requiring the inclusion of css/js files. It was a lot easier to archive and send around the html reports when they were all in one file. But now that there are other files required, the html report is a bit less useful to me. 

Any chance we could include the css/js within the html file? Perhaps this could be enabled only as an option?

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
