### ISSUE TITLE
Cucumber report doesn't contain output generated by Scenario (like printed strings)

### ISSUE THREAD

**Issue by seaman1** [cucumber/cucumber-html#28]
Test case: try to print string

feature file:

```
Feature: Test feature
  Scenario: Print string
    When I print string "my string"
```

procedure file:

```
def printstring(string)
    puts "This is printed string #{string}"
end
```

steps file:

```
And /^I print string "(.*?)"$/ do |string|
  on_page(CommonActions).printstring(string)
end
```

Actual result:
HTML report doesn't contain text output generated by Scenario
(in my case this should be string:
"This is printed string my string")
Console output contains this string.

Expected result:
HTML report should contain output generated by Scenario, like printed strings

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
