### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by stephane-debart** [cucumber/cucumber-html#31]
Hi,
I've found no license information in cucumber-html which makes difficult to use it (and even the whole cucumber) in enterprise context.
Could you please add it ?
Regards,
Stephane

**Comment by mijikim** [comment]
Hello,
Is there an update on this issue? I am having an exact same issue. I submitted a PR with MIT license. Please add a license appropriate to the module or accept the PR.
Thank you!

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
