### ISSUE TITLE
Use with cucumber-js

### ISSUE THREAD

**Issue by gkushang** [cucumber/cucumber-html#33]
How do I configure/create cucumber-html report for cucumber-js?

**Comment by RootMale** [comment]
+1

**Comment by grofit** [comment]
+1

**Comment by gkushang** [comment]
@RootMale @grofit check [this](https://www.npmjs.com/package/grunt-cucumberjs) out for CucumberJS HTML reporting,

https://www.npmjs.com/package/grunt-cucumberjs

![d834bd7e-9756-11e5-80da-66a7c69111c8](https://cloud.githubusercontent.com/assets/3663389/12254833/05abe5a4-b8bb-11e5-9c2b-3e3fef21dc59.png)

**Comment by grofit** [comment]
That looks great, but currently our stuff is gulp :(

**Comment by FastNinja** [comment]
+1

**Comment by mucsi96** [comment]
+1

**Comment by JimTheMan** [comment]
Why is this thread only links to other repositories?? If this is cucumber-html then shouldn't it generate an html from cucumber-js? Isn't that the whole point?

**Comment by paoloambrosio** [comment]
@JimTheMan please read the comment on issue #41 that you raised

Also please note that user support is provided through the [Cukes Google Group](https://groups.google.com/forum/#!forum/cukes)

**Comment by JimTheMan** [comment]
That issue I raised was closed but never answered. The answer was, "In the meantime, you can still use cucumber-html based on the previous example code" but makes no mention of how to do this or even what code is being referred to by "previous example code".

HTH.

**Comment by jbpros** [comment]
@JimTheMan the word "example" links to [the code I was referring to](https://github.com/cucumber/cucumber-js/blob/0af9034e6a18b28623b7e1bd78957c702dd97900/example/example.js).

**Comment by JimTheMan** [comment]
This is just a link to a javascript function. Do I run it with node and then the file? Is it a gulp task? I was expecting an html report.

**Comment by JimTheMan** [comment]
Is there some explanation of usage for this "example" please?

`node example.js`

doesn't seem to do anything.

**Comment by FastNinja** [comment]
Agree with @JimTheMan . Have no idea how to use that.

**Comment by gkushang** [comment]
We've just published [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) for html reports in three different themes. Please check it out.

**Comment by JimTheMan** [comment]
@gkushang Wow, I liked at the bootstrap demo on my phone. OMG so beautiful. And pie charts!! 😍😍😍

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
