### ISSUE TITLE
Rename repository to "cucumber-formatter-html"

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-html#38]
@aslakhellesoy Does it make sense to rename the repository to "cucumber-formatter-html". First when I saw, I asked myself "Woo"... How can a cucumber be implemented in "HTML".

**Comment by maxmeyer** [comment]
Is this formatter really required? It somehow conflicts with the go version. Maybe both should be "merged" - organizationally - ?

**Comment by brasmusson** [comment]
This formatter is currently used by Cucumber-JVM. In the long run it should be replaced with a formatter implemented on the same concept as the new (under development) Cucumber-pretty-formatter.

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
