### ISSUE TITLE
What the F***

### ISSUE THREAD

**Issue by JimTheMan** [cucumber/cucumber-html#41]
Please add usage guide to the REAMDE. How the is anyone supposed to get started with this or integrate it with cucumber.js?? Is this project a complete joke? (because it looks that way from the README).

**Comment by jbpros** [comment]
I find your choice of words quite aggressive. That's not necessary. Please have a look at our [code of conduct](https://github.com/cucumber/cucumber/blob/master/CODE_OF_CONDUCT.md).

cucumber-html is [no longer used](3f5c01006c5378d40c0ddd6890ce1feec685808b) by Cucumber.js. It used to be part of the web-based example.

We have plans for a better cross-implementations html formatter but I can't five you any ETA. In the meantime, you can still use cucumber-html based on the previous [example](https://github.com/cucumber/cucumber-js/blob/0af9034e6a18b28623b7e1bd78957c702dd97900/example/example.js) code.

HTH.

**Comment by JimTheMan** [comment]
"In the meantime, you can still use cucumber-html based on the previous example code."

Ok... how?

**Comment by JimTheMan** [comment]
Is cucumber-html a way to generate the html report or just an html file?
