### ISSUE TITLE
style.css font is ignored

### ISSUE THREAD

**Issue by SuperOok** [cucumber/cucumber-html#46]
In cucumber-html/src/main/resources/cucumber/formatter/style.css the rule
`
.cucumber-report .body {
  font-family: Helvetica,Arial,sans-serif;
}
`
is wrong, because in the generated html document the body element (not class) is not a child of the cucumber-report class.

It must be
`
body .cucumber-report {
  font-family: Helvetica,Arial,sans-serif;
}
`
Note to omit the dot at body as body is no class.

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
