### ISSUE TITLE
insertAdjacentHTML() for faster DOM manipulation?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-html#5]
Just came across this: http://hacks.mozilla.org/2011/11/insertadjacenthtml-enables-faster-html-snippet-injection/

Might be useful. Might be an early optimization.

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this issue is still relevant please direct it there.
